language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
