language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  include:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install

script: vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
